<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE taskset [
  <!ELEMENT taskset (task+)>
  <!ELEMENT task (description?, metafile+, fileset, testset)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT metafile EMPTY>
  <!ELEMENT file EMPTY>
  <!ELEMENT testFile EMPTY>
  <!ELEMENT fileset (file+)>
  <!ELEMENT testset (testFile+)>

  <!ATTLIST task name CDATA #REQUIRED shortName CDATA #REQUIRED >
  <!ATTLIST metafile name CDATA #REQUIRED type (input|output) #REQUIRED alias (in|out) "in" >
  <!ATTLIST file href CDATA #REQUIRED type CDATA #REQUIRED lang CDATA #REQUIRED >
  <!ATTLIST testset points CDATA #REQUIRED timelimit CDATA #REQUIRED memorylimit CDATA "262144" count CDATA #REQUIRED >
  <!ATTLIST testFile href CDATA #REQUIRED  target (in|out) #REQUIRED >
]>
<taskset>
  <task name="Химия" shortName="chemistry">
<!--   Первая задача отбора к олимпиаде ФПМИ-2014  -->
   <metafile name="chemistry.in" type="input" alias= "in"/>
    <metafile name="chemistry.out" type="output" alias= "out"/>
    <fileset>
	<file href="ch_int64.dpr" type="Checker" lang="DELPHI"/>
    </fileset>
    <testset points="1" timelimit="1" count="29">
	<testFile target="in" href="chem/tests/##.i"/>
	<testFile target="out" href="chem/tests/##.o"/>
    </testset>
  </task>
  <task name="Шахматы" shortName="chess">
<!--   Вторая задача отбора к олимпиаде ФПМИ-2014  -->
   <metafile name="chess.in" type="input" alias="in"/>
    <metafile name="chess.out" type="output" alias="out"/>
    <fileset>
      <file href="ch_string.dpr" type="Checker" lang="DELPHI"/>
    </fileset>
    <testset points="1" timelimit="1" count="31">
	<testFile target="in" href="chess/tests/##.i"/>
	<testFile target="out" href="chess/tests/##.o"/>
    </testset>
  </task>
</taskset>
